### ISSUE TITLE
Memory Link name

### ISSUE THREAD

**Issue by dsoldier** [suloku/BW_tool#3]
So, I don't know if it's on purpose but, every time I put my BW save in BW2 memory link, everyone acknowledges my past character as suloku.

**Comment by suloku** [comment]
If you are importing from a BW save no, that's not intentional.

The memory link structure is not fully know, so it's more an unlocker than an editor. It puts my own complete memory link data I got from BW2 after importing (which has everything).
This unlocks all memories, the props case (which is optional), the special battles, N's pokemon and puts 3 trophies in BW1 room. 

Importing from BW 1 save only changes some of that data, like hall of fame and trainer name, which for what you say isn't being correctly done. I'll look at it this afternoon, can you tell me where can I find an npc that talks about the BW1 trainer?

ps: a full editor would be ideal, but my main goal was to provide a means to enjoy full BW2 experience even if you haven't played BW1 or are using an emulator, that's why the memory link in the tool is more a "unlock all".

**Comment by syahmudap** [comment]
You can find an NPC that mention BW Character at Route 1. The one that brags about how he helped save the world because he tells the BW Protagonist about how to caught a wild pokémon.

**Comment by syahmudap** [comment]
I managed to find a way to change the trainers name to be your own.
The way this done is by using a Hex editor.
Open the .mld file with the HxD and search a word with S.u.l.o.k.u (there's spacing in the name with 00 hex code) just replace the word with your desired name. I don't if it will work with a name more or less than 6 words, because it just so happens that mine is also 6 words (with mine replacing S.u.l.o.k.u with V.e.c.t.o.r).

But I only managed to edit the BW char's name. I don't know what's the other purpose, tho.

![Screenshot_2020-05-18-14-05-41-407_com dsemu drastic](https://user-images.githubusercontent.com/65528881/82184223-7b478580-9911-11ea-88f2-c5a786fd0733.jpg)

**Comment by suloku** [comment]
Sorry for the very late reply. I've just tested myself and I did not have any problem, the name was changed when importing from a BW1 savegame or manually editing. I did notice a coding error where hall of fame data was not being properly imported. It isn't used in the game to my knowledge so I didn't notice until now since my trainer name in my bw save and b2w2 save was the same.

I'll be updating the program today, if you may still be willing to test if it correctly changes names it'd be helpful.
